apiVersion: v2
name: jupyterhub-groups-exporter
description: A Helm chart for deploying the jupyterhub-groups-exporter service on Kubernetes.
type: application
version: 0.0.1-set.by.chartpress
appVersion: "0.1.0"
