replicas: 1

image:
  repository: quay.io/2i2c/jupyterhub-groups-exporter
  tag: "latest"

config:
  groupsExporter:
    update_exporter_interval: 10

extraEnv:
  - name: JUPYTERHUB_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: hub
        key: hub.services.jupyterhub-groups-exporter.apiToken

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 8100

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {
  prometheus.io/scrape: "true",
}

podLabels: {
  hub.jupyter.org/network-access-hub: "true"
}
