config:
  groupsExporter:
    update_info_interval: 3600
    update_metrics_interval: 15
    update_dirsize_interval: 7200
    log_level: INFO

extraEnv:
  - name: JUPYTERHUB_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: hub
        key: hub.services.jupyterhub-groups-exporter.apiToken
  - name: PYTHONUNBUFFERED
    value: "1"

image:
  repository: quay.io/2i2c/jupyterhub-groups-exporter
  tag: "set-by-chartpress"

service:
  type: ClusterIP
  port: 8100

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations:
  {
    prometheus.io/scrape: "true",
    prometheus.io/port: "8100",
    prometheus.io/path: "/services/groups-exporter/",
  }

podLabels: { hub.jupyter.org/network-access-hub: "true" }
